language: node_js
node_js:
  - 6
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database vagrant;' -U postgres
  - psql -c "CREATE USER vagrant WITH PASSWORD 'vagrant';" -U postgres
  - sudo npm run migrate
after_success:
  - "./coverage/test-coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
